### ISSUE TITLE
question: ovmfvartool as a library

### ISSUE THREAD

**Issue by baloo** [hlandau/ovmfvartool#1]
Hi @hlandau,

I'm a fan of the approach you're taking to work with OVMF var files, and I'd like to use it for our secureboot test harness on nixos.
I was wondering if you would be open to a contribution to get ovmfvartool to expose a library and make it a standard python package.

I would retain the current behavior of the tool to work in a CLI, but getting it exposes through a library would make integration in the nixos vm driver (written in python) slightly easier.

Anyhow, thanks for your work!

cc @RaitoBezarius

**Comment by baloo** [comment]
For some context on how I intend to use the API:
https://github.com/RaitoBezarius/nixpkgs/pull/2/files

**Comment by hlandau** [comment]
Thanks for the PR, which I've merged.

I use NixOS myself so do let me know how this goes / @mention me in any nixpkgs PR you raise. Any questions, feel free to raise another issue. Good luck!
